feat lab3, Sobolev Daniil
Parampaika/OS_labs pull request #3
Opened 2023-12-16 14:33 UTC by Parampaika

2023-12-16 14:34 UTC, Parampaika commented
Аргументы:
WRITERS_NUM
READERS_NUM
THREADS_WRITERS
THREADS_READERS
TIME_ITERATIONS

2023-12-16 14:38 UTC, Parampaika commented
Делал только одну структуру (множество с “ленивой” синхронизацией)

2023-12-19 08:57 UTC, DariaWelt requested changes
Программа работает. Добавьте build.sh файл

2023-12-24 07:39 UTC, DariaWelt approved these changes
Работа зачтена

2023-12-24 07:39 UTC, merged